name: cloudapp-demo-todo-list

replicaCount: 1

# 这里的 ${packageId} 要替换成实际的 packageId
image: cloudapp.tencentcloudcr.com/${packageId}/cloudapp-demo-todo-list:v202407171102

service:
    enabled: true
    appProtocol: true

    annotations: {}
    labels: {}
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []

    enableHttp: true
    enableHttps: true
    ipFamilyPolicy: "SingleStack"
    ipFamilies:
      - IPv4

    ports:
      http: 80
      https: 443

    targetPorts:
      http: 8000
      https: 8000

    type: NodePort

    nodePorts:
      http: 8000
      https: ""
      tcp: 8000
      udp: {}

    external:
      enabled: true

    internal:
      enabled: false
      annotations: {}
      loadBalancerSourceRanges: []

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

# 应用运行时注入
cloudappTargetSubnetID: ""
cloudappClusterSecurityGroup: ""
cloudappImageCredentials:
  registry: ""
  username: ""
  password: ""
mysql:
  host: ""
  port: ""
  user: ""
  password: ""